#!/bin/sh

valid_command() {
	command -v "$1" >/dev/null 2>&1
}

list_packages() {
	if valid_command pacman; then
		pacman -Qqe
	elif valid_command apk; then
		apk info | grep -x -f /etc/apk/world
	else
		printf "No supported package manager found\n" >&2
		exit 1
	fi
}

File="${XDG_CONFIG_HOME:-$HOME/.config}/spy/update"

[ -r "$File" ] && . "$File"

list_packages | sort
